package com.group14.irecycle.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

// Database listing 
@Entity
@Table(name = "listing")
public class Listing {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long id;
	
	@Column(nullable = false)
	private String title;
	
	@Column(nullable = false)
	private String description;
	
	// links to user table
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "listing")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
	private User user;
	
	// links join table for saved listings
	@ManyToMany(mappedBy = "savedListings", fetch = FetchType.LAZY)
    private Set<User> users = new HashSet<>();

	public Listing() {}
	
	public Listing(String title, String description, User user) {
		super();
		this.title = title;
		this.description = description;
		this.user = user;
	}
	
	// autogenerated getters and setters
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}
}
