package com.group14.irecycle.model;

import java.sql.Date;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

// // Database past listing table
@Entity
@Table(name = "past_listing")
public class PastListing {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long id;
	
	@Column(nullable = false)
	private String title;
	
	@Column(nullable = false)
	private String description;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
	private User user;
	
	@Column(nullable = false)
	private boolean completed;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipient")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
	private User recipient;
	
	@Column(nullable = false, name = "date_closed")
	private Date closedDate;

	public PastListing() {}

	public PastListing(String title, String description, User user, boolean completed, User recipient,
			Date closedDate) {
		super();
		this.title = title;
		this.description = description;
		this.user = user;
		this.completed = completed;
		this.recipient = recipient;
		this.closedDate = closedDate;
	}
	
	//setters for different date formats
	public void setClosedDate(LocalDate closedDate) {
		this.closedDate = Date.valueOf(closedDate);
	}
	
	public void setClosedDate(String birthDate) {
		this.closedDate = Date.valueOf(birthDate);
	}
	
	public void setClosedDate(Date birthDate) {
		this.closedDate = birthDate;
	}

	//autogenerated getters and setters
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public boolean isCompleted() {
		return completed;
	}

	public void setCompleted(boolean completed) {
		this.completed = completed;
	}

	public User getRecipient() {
		return recipient;
	}

	public void setRecipient(User recipient) {
		this.recipient = recipient;
	}

	public Date getClosedDate() {
		return closedDate;
	}
	
}